name: Permohonan Menerbitkan Blog ke EDU
description: Ajukan blog Anda untuk diterbitkan di platform EDU.
title: "[Blog Submission] "
labels:
  - blog
body:
  - type: markdown
    attributes:
      value: |
        Silakan isi form berikut dengan teliti. Setelah mengirimkan blog, jangan mengubah konten artikel lagi. Setelah disetujui, jangan menutup issue sendiri, karena administrator akan menambahkan informasi ke basis data secara manual.

  - type: input
    id: blog_title
    attributes:
      label: Judul Blog*
      description: Contoh: Cara Menggunakan Resend di Nuxt.js
      placeholder: ex, Cara Menggunakan Resend di Nuxtjs
    validations:
      required: true

  - type: input
    id: blog_url
    attributes:
      label: Situs Tempat Blog Berada*
      description: Harap gunakan URL HTTPS yang valid.
      placeholder: ex, https://nlfts.link
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Peringatan: Blog setidaknya harus pernah diterbitkan di platform lain, harus berupa situs web HTTPS, dan harus dapat diakses. Situs yang tidak dapat diakses atau tidak memuat blog akan ditolak.

  - type: checkboxes
    id: blog_categories
    attributes:
      label: Kategori Blog*
      description: Pilih satu atau lebih kategori yang sesuai.
      options:
        - label: Teknologi
        - label: Pribadi
        - label: Developer
        - label: Tips & Trik
        - label: Tutorial
        - label: Lainnya
    validations:
      required: true

  - type: input
    id: blog_category_other
    attributes:
      label: Kategori Blog Lainnya
      description: Jika Anda memilih opsi Lainnya, tulis kategori yang dimaksud.
      placeholder: ex, Keuangan

  - type: textarea
    id: blog_description
    attributes:
      label: Deskripsi Blog*
      description: Jelaskan secara singkat isi blog Anda.
      placeholder: ex, Blog ini membahas tentang cara menggunakan Resend di Nuxt.js.
    validations:
      required: true

  - type: textarea
    id: blog_notes
    attributes:
      label: Catatan
      description: Jika ada hal lain yang ingin Anda sampaikan, tulis di sini.
      placeholder: ex, catatan.

  - type: checkboxes
    id: confirmation
    attributes:
      label: Mohon Konfirmasi Hal Berikut*
      description: Centang semua poin berikut untuk melanjutkan.
      options:
        - label: Saya telah membaca dengan saksama kriteria inklusi dan bagian Tanya Jawab, serta memenuhi kriteria inklusi.
        - label: Saya memahami lisensi CC BY NC yang akan diterbitkan di EDU.
        - label: Informasi saya benar. Saya akan segera memberi tahu Anda jika ada perubahan, seperti URL yang diperbarui.
    validations:
      required: true
